### ISSUE TITLE
NullPointerException: Cannot get property 'headerPhoto' on null object

### ISSUE THREAD

**Issue by neftalyluis** [neftalyluis/course-manager#12]
https://sentry.io/neftaly/amor-a-mi/issues/409327785/

```
NullPointerException: Cannot get property 'headerPhoto' on null object
    at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
    at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
    at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
    at gsp_course_manager_coursegetLesson_gsp$_run_closure2.doCall(gsp_course_manager_coursegetLesson_gsp.groovy:34)
...
(122 additional frame(s) were not displayed)

Full Stack Trace:
```

**Comment by neftalyluis** [comment]
Hay que crear un Interceptor que verifique las urls

**Comment by neftalyluis** [comment]
Agregué el interceptor y también empecé a exponer un log para cuando ocurra, me suena a que es un bug mas grandote, Cierro
